# Generated by Django 5.0.3 on 2024-03-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='massage',
            new_name='body',
        ),
    ]
