# Generated by Django 5.0.3 on 2024-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_massage_contact_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(upload_to='post-video/'),
        ),
    ]
